### ISSUE TITLE
Doesn't install expect?

### ISSUE THREAD

**Issue by project707** [rjaros87/chef-expect#3]
I'm on Centos, with _everything_ installed by Chef and if I try to use the expect cookbook as stated in the docs, I get an error that there is no expect command. I notice this case for my OS:

```
when 'debian', 'rhel'
  package 'expect'
when 'mac_os_x' ...
```

It never issues a command (like install) for the expect package

**Comment by rjaros87** [comment]
> It never issues a command (like install) for the expect package

So propably you try call `expect` command before the expect package is installed?

Tomorrow I'm going to run tests, so I will see if something went wrong.

**Comment by project707** [comment]
That could be possible, but I'm setting:

```
depends 'expect', '~> 2.0.0'
```
in my metadata.rb (for any server that uses my cookbook), and then only using it in the last command in my default recipe. I believe that should work - it's how we are using many other cookbooks.

Also, it doesn't freak out about "expect_script", it only breaks once it gets into the expect command within that block.

I also noticed that there was no install for the expect package when I run chef-client on the server. I think there should have been some sort of output for that.

**Comment by rjaros87** [comment]
Did you include the recipe in your recipe (`include_recipe 'expect_script'`)? or put expect recipe on run list in properly (earlier) position (`recipe[expect]`)?

Dependencies to 'expect' cookbook doesn't install expect package ;)

**Comment by project707** [comment]
I could totally be missing something obvious, but with:
```
depends 'expect', '~> 2.0.0'
```
in my metadata.rb

and:
```
include_recipe 'expect_script'
```
at the top of my recipes/default.rb

I get a new error:
```
ERROR: Cookbook expect_script not found. If you're loading expect_script from another cookbook, make sure you configure the dependency in your metadata.
```
Also, it never failed on "expect_script" itself - that ran before. It failed on running the _"expect" command itself_ while using the "expect_script" convention to do it.


> Dependencies to 'expect' cookbook doesn't install expect package ;)

But the cookbook does, right? I can't see where the cookbook installs it (except for windows/cygwin), but the readme clearly states:
> This cookbook will install [Expect package](http://expect.sourceforge.net/).

In addition (though unrelated), the cookbook forces dependencies of windows, cygwin, and homebrew cookbooks, regardless of which os it is being used on.


Anyhow I have worked around this, but it seems like it's not ensuring the existence of the package for any os but Windows with Cygwin

**Comment by project707** [comment]
I take that back. I did obviously see the following as I (originally) stated above:

```
when 'debian', 'rhel'
  package 'expect'
```
which defaults to "install"

This has to either be an issue on my side or something wrong with the os check in our version. I would guess this can be closed and I will try to figure out what's happening there.

**Comment by project707** [comment]
And yeah... I was using the wrong name/convention to include the recipe. That was what was happening in the error I mentioned when i changed it to the include you mentioned.

Problem solved, sorry for the trouble.
